server:
  port: 50000
spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://101.37.158.206:3306/dStore_member
  application:
    name: dStore_member
mybatis-plus:
  mapper-locations: classpsth:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.mxw.member.mapper:
      debug
